### ISSUE TITLE
Show demo

### ISSUE THREAD

**Issue by higimo** [SudoDotDog/BWNL-Horizon-React#1]
please

**Comment by WMXPY** [comment]
![horizon demo](https://user-images.githubusercontent.com/5085821/82339580-d0d46e80-99b3-11ea-9b98-9dd13be54179.gif)

I'd love to.

**Comment by higimo** [comment]
@WMXPY plese add this in README.md

**Comment by WMXPY** [comment]
Thanks for your suggestion
